### ISSUE TITLE
Search Query

### ISSUE THREAD

**Issue by clsource** [vaibhavmule/awesome-masonite#2]
Hello, maybe this query would help in the process of discovering more masonite related projects

https://api.github.com/search/repositories?q=masonite&language=python&sort=stars&order=desc

👍

**Comment by vaibhavmule** [comment]
How shall we incorporate into this awesome-masonite?

Awesome Masonite, now it has `README.md` and it is available on a website. https://vaibhavmule.com/awesome-masonite/

Maybe creating a directory of `packages` and just adding index.html and some js files.
